_posts/elements/2015-02-04-example-kitchen-sink.md
index.html

@talbs FYI
I like to display block-level elements as blocks and inline-level elements as inline. I think this helps reinforce what the element is and aids in scanning the markup to make changes. Plus it helps ensure that tags are closed properly.
The blockquote fix is here too. You didn't close the `</strong>`tag and the `blockquote` never closed as a result. Should be good to go now though!
Exciting.

Formatting tweaks

---

.gitignore
404.html
README.md
_config.yml
_includes/assets-primary.html
_includes/assets-secondary.html
_includes/element.html
_includes/footer.html
_includes/head.html
_includes/header.html
_includes/navigation.html
_layouts/default.html
_layouts/documentation.html
_layouts/element.html
_layouts/page.html
_posts/elements/2015-02-04-example-kitchen-sink.md
_posts/elements/2015-02-20-example-element.md
about.md
index.html
public/pl-static/css/syntax.css

This work adds in basic Jekyll install + site structure
* configuring Jekyll blog settings
* configuring post/element metadata
* creating basic UI architecture
* architecting basic index + element templates
* adding sample posts/elements
* updating README file

Setup: Initial Jekyll Config (UX-1598)

---

_posts/elements/2015-03-25-headings.md
_src/static/sass/components/_headings.scss
_src/static/sass/utilities/_variables.scss
public/css/main-ltr.css
public/css/main-rtl.css

* trimmed down examples
* added emphasis styling
* revised base and de-emphasis styling
* minor comment changes

Revising Heading Rendering

---

_posts/elements/2015-03-25-headings.md
public/css/main-ltr.css
public/css/main-rtl.css

This cleaned up branch replaces https://github.com/edx/ux-pattern-library/pull/24
@talbs FYI

Elements: Headings

---

_posts/elements/2015-03-25-headings.md
_src/static/sass/components/_headings.scss
_src/static/sass/utilities/_variables.scss
public/css/main-ltr.css
public/css/main-rtl.css

adding in missing heading lvl 5 (and adjusting remainder of scale)

Fix - Missing Heading

---

_posts/elements/2015-04-01-colors.md
_src/pl/static/sass/_views.scss
_src/static/sass/components/_colors.scss
public/css/main-ltr.css
public/css/main-rtl.css
public/pl/css/main.css

@talbs This syncs up the example wrappers for our color palettes.

Fixup - Adjusting example set to be reusable

---

_posts/elements/2015-03-25-headings.md
_posts/elements/2015-04-01-colors.md
_posts/elements/2015-04-09-buttons.md
_src/pl/static/sass/_components.scss
_src/pl/static/sass/_utilities.scss
_src/pl/static/sass/_views.scss
_src/static/sass/_build.scss
_src/static/sass/components/_buttons.scss
_src/static/sass/utilities/_helpers.scss
_src/static/sass/utilities/_variables.scss
public/css/main-ltr.css
public/css/main-rtl.css
public/pl/css/main.css

This pull request establishes Sass partials for our buttons and contains a demo page that displays them all using our created styles.
**Buttons with icons are not yet included as we don't have a finished set of icons to incorporate.**

Elements: Buttons

---

_posts/elements/2015-05-12-forms.md

The forms branch was merged without including the `for`/`id` update. This pulls that quick fix in. Merging since thumbs were implied after Frances's feedback.

!fixup - missed if and for update

---

_posts/elements/2015-04-01-colors.md

A quick clean up that's needed from some loose ends on https://github.com/edx/ux-pattern-library/pull/86

FIX: correcting @include palette() values for color listings

---

README.md

This work adds @frrrances to the list of contributors on this project (given her sweet sweet favicon work - https://github.com/edx/ux-pattern-library/pull/90).
- - -

Admin: Props to Frances Botsford as Contributor

---

bower.json

Corrections made after merge of #123.
@talbs @clintonb

Changed bower version number and added font path prefix

---

README.md

Added myself to README (Contributors) 

---

_src/pattern-library/sass/utilities/_variables.scss
_src/pldoc/static/sass/_utilities.scss

This work does some quick housekeeping of Pattern Library source Sass variables based on feedback and proactive formatting/dusting.
- - -

FIX - General Clean up of Sass Variables

---

README.md
bower.json

See https://github.com/edx/ux-pattern-library/blob/talbs/readme-add-dependencies/README.md for a preview of changes made.
- - -

Add Third Party and General Dependencies to README

---

_src/pattern-library/sass/utilities/_variables.scss
_src/pldoc/static/sass/_components.scss

This quick work adds in some quick configuration for static asset (fonts and images) path Sass variables in the edx-pattern-library.
- - -

Add/Re-organize Path-Based Sass Variables

---

CHANGELOG.md
bower.json
pattern-library/sass/utilities/_variables.scss

This work adds in a convention for customizing specific font-face paths (since font assets may be stored/referenced elsewhere in projects).
- - -

Abstract Font Face Paths for Customization

---

_includes/assets-primary.html
_includes/assets-secondary.html
_includes/canvas-assets-primary.html
_includes/canvas-assets-secondary.html

This work corrects broken asset paths (CSS and JS) for element example views.

FIX - PL Doc: Correcting Example View Asset Paths

---

index.html

fixes an unclosed button element on the Preview tab

---

_posts/elements/2015-03-25-headings.md
_posts/elements/2015-04-09-buttons.md
_posts/elements/2015-05-12-forms.md
_posts/elements/2015-07-01-grid.md
examples/kitchen-sink.html

Replacing empty link href attrs with dummy ux.edx.org URL
- - -

PL Doc: Addressing Issue #175

---

CHANGELOG.md
bower.json

This work updates bower package prefs to ignore moved pldoc assets (see https://github.com/edx/ux-pattern-library/pull/165).
- - -

FIX - Ignore Preferences in Bower Package

---

gulp/tasks/pldoc_styles-minify.js
gulp/tasks/scripts-uglify.js
gulp/tasks/styles-minify.js

This work removes redundant/already run tasks from styles/scripts optimization.

PL Doc: Removing Redundant Steps from Gulp Optimizations

---

AUTHORS
README.md

I fixed some typos and rendering errors while going through the documentation.
@talbs & @andy-armstrong, please review.

Updated README.

---

pattern-library/sass/global/_mixins.scss
pattern-library/sass/patterns/_forms.scss

Removed pointer cursor from progress bar (in the forms section) on hovering.

Removed pointer from progress bar hover.

---

CHANGELOG.md
bower.json
package.json

Increment version for progress bar cursor fix.

Increment version for progress bar cursor fix.

---

_config.yml
bower.json
package.json

Update pattern library email address

---

CHANGELOG.md
_posts/patterns/2016-01-28-alerts.md
bower.json
package.json
pattern-library/sass/_edx-pattern-library.scss
pattern-library/sass/patterns/_alerts.scss
pldoc/static/sass/_components.scss

Added alerts pattern.
- ~~UI/Visual Design & Code review: @talbs~~ N/A

Added alerts pattern.

---

_posts/patterns/2016-01-28-alerts.md

Update alert icon classes to use new names.

Updated alert icon classes.

---

.pr_cover_letter.md.j2

I'm going to merge this as an experiment...
FYI @AlasdairSwan @dan-f

Add a PR cover letter

---

_posts/patterns/2016-01-28-alerts.md

Fix a typo

---

CHANGELOG.md
bower.json
package.json

@andy-armstrong this is the version bump to try and get the doc site updating.

Updated to version 0.11.1

---

CHANGELOG.md
bower.json
package.json

- Improve how dependencies are handled via import paths
@AlasdairSwan @bjacobel @dan-f - please review (one of you)

Release 0.12.0

---

CHANGELOG.md
bower.json
package.json

* Added checks to edx-icons.js to ensure it loads with or without RequireJS

Release 0.12.4

---

CHANGELOG.md
bower.json
gulp/tasks/build-production.js
package.json

Cutting a new 0.12.5 release primarily to include the fix for the libsass compilation bug.

Release 0.12.5

---

CONTRIBUTING.md

Replace misplaced reference to UITK with UXPL

---

.mention-bot

See description here: https://github.com/edx/edx-ui-toolkit/pull/79

Add some config for the mention bot

---

CHANGELOG.md
bower.json
package.json

Bump version
UX Pattern Library now uses Font Awesome
http://ux-test.edx.org/alisan/fa-icon-tnl-4697/
- [] @andy-armstrong 

Release 0.14.0

---

CHANGELOG.md
bower.json
package.json

0.15 release, contains breadcrumbs pattern and styles.

Release 0.15.0

---

CHANGELOG.md
README.md
bower.json
package.json

[TNL-4902](https://openedx.atlassian.net/browse/TNL-4902)
Bump version
Update GitHub page third party dependencies:  AFontGarde to FontAwesome
[Preview](http://ux-test.edx.org/alisan/remove-edx-icons-js/)

Release 0.16.0

---

CHANGELOG.md
bower.json
package.json

Clean up release: remove edx-icons font variable

Release 0.16.1

---

package.json
pattern-library/sass/global/_helpers.scss
pattern-library/sass/global/_mixins.scss
pattern-library/sass/global/_settings.scss
pattern-library/sass/patterns/_alerts.scss
pattern-library/sass/patterns/_breadcrumbs.scss
pattern-library/sass/patterns/_buttons.scss
pattern-library/sass/patterns/_depth.scss
pattern-library/sass/patterns/_dropdown-menu.scss
pattern-library/sass/patterns/_forms.scss
pattern-library/sass/patterns/_headings.scss
pattern-library/sass/patterns/_lists.scss
pattern-library/sass/patterns/_tables.scss
pldoc/_components/alerts.md
pldoc/_design_elements/colors.md
pldoc/static/js/color-contrast.js
pldoc/static/js/colors.js
pldoc/static/js/colors_json.js
pldoc/static/js/ui.js
pldoc/static/sass/_components.scss
pldoc/static/sass/_layouts.scss
pldoc/static/sass/_utilities.scss
pldoc/static/sass/_views.scss

This work updates our color palettes to provide primary and secondary values that work on both white and our light gray.
Previously, our core blue and core pink did not work on gray and in some cases, they barely worked on white. As developers begin to utilize the pattern library and our colors more heavily, we needed to provide options that won't cause accessibility failures in tests and that allow for an easy, consistent approach to development.
Along with updated colors, with the help of the UX team, I've simplified the number of options. Our primary color palettes was reduced from 10 to 5, with the base options being accessible on both white and gray. I've eliminated our "information" color altogether, per UX request. I've also reduced our grayscale sets to just one, basing the gray …

Updating color palettes and color swatch layout

---

CHANGELOG.md
bower.json
package.json

Release 0.16.3

---

CHANGELOG.md
bower.json
package.json

Release 0.16.4

---

CHANGELOG.md
bower.json
package.json

Releasing version 0.16.5
- Fixes for button styling, along with button documentation clean up
@bjacobel @clrux please review

Release 0.16.5

---

CHANGELOG.md
bower.json
package.json

- Fixes for color contrast with form fields
@bjacobel @clrux please review.

Release 0.16.6

---

README.md

Fix link to contributor guidelines

---

CHANGELOG.md
bower.json
package.json

Release 0.16.7
- FEDX-228
- FEDX-242
- FEDX-243

Release 0.16.7

---

CHANGELOG.md
bower.json
package.json

Release 0.17.1

---

README.md

Removed reference to susy in readme.

Removed reference to susy in readme.

---

CHANGELOG.md
bower.json
package.json

I will not merge this until 11/17.
@thallada @AlasdairSwan @alisan617 @andy-armstrong @bjacobel 
CC: @chris-mike

Release 0.18.0

---

bower.json

@dsjen @andy-armstrong @AlasdairSwan please review

Corrected license identifier in bower.json

---

.mention-bot

https://openedx.atlassian.net/browse/FEDX-329

kill mention bot

---

.github/workflows/ci.yml

build: upgrading ubuntu version to 20.

build: upgrading ubuntu version

---

.github/workflows/commitlint.yml

This PR updates the org references in CI workflows
Issue: https://github.com/edx/.github/issues/28

fix: update org references

---

.github/workflows/ci.yml
Gemfile.lock

Bumps [ffi](https://github.com/ffi/ffi) from 1.9.10 to 1.15.5. …

build: Bump ffi from 1.9.10 to 1.15.5

---

.github/workflows/ci.yml
Gemfile.lock

build: bump gem version wrt ruby version 2.7

---

package-lock.json
package.json

build: update edx-ui-toolkit

---

package-lock.json
package.json

build: update lock file

---

package-lock.json

- Bump **jquery**, **moment-timezone**, **underscore**, **js-yaml**, **is-svg** and **ajv** in order to resolve security issues.
leave this section blank if you do not know who to tag, and we …

chore:  update packages to resolve vulnerabilities 

---

package-lock.json

Bump ajv to **6.12.3**
TODO: You can use the checklist below …

build: bump ajv
