edx/ux-pattern-library

_layouts/element.html, _src/pl/static/sass/_base.scss, _src/pl/static/sass/_components.scss, index.html, public/pl/css/main.css
This work builds on https://github.com/edx/ux-pattern-library/pull/30's work of adding tabs into element renderings on the documentation/preview site.
=> PL: Revising Element Tabs Structure + Styling

_posts/elements/2015-04-01-colors.md, _src/pl/static/sass/_components.scss, _src/pl/static/sass/_layouts.scss, _src/pl/static/sass/_utilities.scss, _src/static/sass/components/_colors.scss, public/css/main-ltr.css, public/css/main-rtl.css, public/pl/css/main.css
This work makes the UI of the PL documentation site responsive in a simple way. Navigation is merely hidden at smaller breakpoints for the time being. 
This should be augmented going forward once the navigation is more central to the UX of the site.
=> PL: Making Documentation Site Responsive

_posts/elements/2015-04-09-buttons.md
@talbs This really quick PR changes the link/button `href` from `#` to `edx.org`.
=> Changing links from # to edx.org

_posts/elements/2015-03-25-headings.md
This work updates our doc site headings example to use copy elements for context
=> PL: headings + copy sync up

_includes/head.html
This work sets favicon path to be site/root-relative so pages like http://ux.edx.org/elements/buttons/ can render it as well.
=> FIX: Correct Path so Favicon Displays on All PL Doc Views

gulp/config.js, gulp/tasks/watch.js
This work changes our local gulp workflow's watch task to watch more Jekyll-based file changes, including:
* HTML/DOM includes
* Layouts
* Example files (in ``/examples/*.html``)
This work should make any local template or copy changes much more efficient.
=> Set Up: Watch All Jekyll Files

gulp/tasks/default.js
This work removes a redundant ``jekyll-build`` task being run as part of our ``default`` gulp task. Jekyll will be kicked off from the ``watch`` task called as part of that ``default`` task.
**Before: Local Terminal Output from Gulp Command**
```
ux-pattern-library :: (master) » gulp                                                                                                              ~/edX/ux-pattern-library
[08:01:27] Using gulpfile ~/edX/ux-pattern-library/gulpfile.js
[08:01:27] Starting 'default'...
[08:01:28] Starting 'styles'...
[08:01:28] Starting 'pldoc_scripts-lint'...
[08:01:28] Starting 'images'...
[08:01:28] Finished 'default' after 25 ms
[08:01:28] gulp-imagemin: Minified 0 images
[08:01:28] Finished 'images' after 20 ms
[08:01:28] Finished 'pldoc_scripts-lint' after …
```
=> Set Up: Remove Extra Jekyll Build Step from Gulp Default Task

_src/pattern-library/sass/components/_grid.scss
This work removes the debug grid extend/utility - it is not used and is causing compilation issues
=> FIX: Remove Grid Debug Utility

_src/pattern-library/sass/utilities/_variables.scss
This work, based off of good feedback from @frrrances, simplifies how we use ``$baseline`` and the ``spacing-vertical/horizontal``settings in the PL. 
Essentially, ``$baseline-vertical`` and ``$baseline-horizontal`` are not needed and we can just scale vertical and horizontal spacing within the $spacing-`` sass maps.
- - -
=> FIX - Simplifying Sass baseline/spacing variables

_src/pattern-library/sass/components/_copy.scss, _src/pattern-library/sass/components/_headings.scss
**Description**
This small PR adds extends to allow for emphasized copy and headings without needing to add classes to the DOM.
**Reviewers**
=> Add emphasized headings and copy extends

README.md
This work updates the docs to note and explain the need for the ``_lib.scss`` partial in any app using the edx-pattern-library bower package.
=> Update README with Per-app Sass Compilation Import Changes

_config.yml, _layouts/element.html, _posts/elements/2015-03-25-headings.md, _posts/elements/2015-04-09-buttons.md, _posts/elements/2015-04-27-copy.md, _posts/elements/2015-05-12-forms.md, _posts/elements/2015-07-01-grid.md, _posts/elements/2015-07-10-layouts.md, _posts/elements/2015-07-21-depth.md, index.html
This work fixes and abstracts even more scss link paths per element in the documentation site. This got out of whack with the recent directory changes needed to make the pattern library a versioned Bower Package.
- - -
=> FIX - PL Doc: Correcting scss link paths for elements

gulp/config.js, gulp/tasks/clean.js, gulp/tasks/default.js, gulp/tasks/fonts.js, gulp/tasks/icons.js
This work adds in quick support for moving both icons and fonts to the proper UXPL Documentation Site paths needed for both production and for local development.
**NOTE**: This work only moves assets using the default gulp task (running ``gulp``). It does not watch assets yet. A follow-on PR will tackle that.
- - -
=> PL Doc: Add in Additional Asset Tasks to Gulp Workflow

.bowerrc
This work adds a .bowerrc file to firm up location of installed packages to help override any local dev global settings when individuals are running the PL Doc Site locally.
- - -
=> PL Doc: Set where Bower packages are installed

README.md
This corrects some updated heading and skip links in the README.
- - -
=> FIX: Correcting Broken ToC links in README

gulp/config.js, gulp/tasks/build-development.js, gulp/tasks/build-production.js, gulp/tasks/default.js, gulp/tasks/styles.js
This work takes the good recommendation @frrrances had, and the practice that I've personally set up at https://github.com/talbs/mise-en-place/tree/master/gulp/tasks, and creates ``build-production`` and ``build-development`` Gulp tasks. the ``default`` task has been simplified and now uses the ``build-development`` task.
Additionally, the ``styles`` task and config settings have been revised to:
* not contain any production-centric steps (minifying CSS now happens within ``build-production``, which should be run before committing any compiled assets.)
* remove any production-centric settings that were not being used by the new tasks.
- - -
=> PL Doc: Abstract Production/Development Build-centric Gulp Tasks

CHANGELOG.md, bower.json, pattern-library/sass/utilities/_helpers.scss
Per the fix noted in https://github.com/edx/edx-platform/pull/10405, this work proactively adds in some Sass placeholder utilities for use alongside the Pattern Library
- - -
=> Adding text truncation and wrapped Sass placeholders

_posts/patterns/2015-07-01-grid.md
Drive-by contribution. I noticed the current placeholder images don't look so hot on high-resolution displays. This PR includes a commit bumping the sizes of the placeholder images. For example, here's before:
And here's after:
@talbs, impressions? How do you deploy to http://ux.edx.org/?
=> Increase placeholder image sizes

_posts/patterns/2015-04-09-buttons.md
This work aims to adjust the instructions and information around the button pattern's visual styling to help users of the UXPL choose the appropriate semantic element/markup for their needs (regardless of styling).
- - -
=> FIX - Using an Example of a Link as a Button

.npmignore, CHANGELOG.md, bower.json, package.json
I've removed the demo directory from the npm and bower packages, and bumped the version number.
=> Remove demo directory from the public packages

CHANGELOG.md, bower.json, package.json, pattern-library/sass/global/_reset.scss
This work removes a reference to a deleted Sass extend that is no longer used, ``%reset-copy``.
=> FIX - Removing Reference to Deleted Sass Extend

CHANGELOG.md, bower.json, package.json, pattern-library/sass/patterns/_lists.scss
This work removes the unused ``.list-links``/``%list-links`` extend from buttons Sass.
=> FIX - Remove Unused "list-links" Rules

CHANGELOG.md, bower.json, package.json, pattern-library/sass/patterns/_buttons.scss
This work removes the unused ``%btn-base`` extend from buttons Sass.
=> FIX - Removing Unused Extend from Buttons Sass

CHANGELOG.md, bower.json, package.json, pattern-library/sass/patterns/_buttons.scss
This fix publishes some missing code that was meant to be published with https://github.com/edx/ux-pattern-library/pull/273. For some reason this code change was not picked up in our ``0.8.11`` package version.
=> FIX - Publishing Missing Buttons Sass Extend Solution

CHANGELOG.md, README.md, bower.json, package.json
This work aims to make the README file a bit easier to parse as well as make some of its content a bit more centralized from a management and documentation point of view. Here are some highlights:
* The entire how-to set of instructions (including how to use the package, develop on the package, and spin up/develop on the documentation site) has been moved to the repo's main wiki page
* Since our public package name is "edx-pattern-library", I've tried to sync up as many older name references (i.e. UXPL, edX UX Pattern Library) to just be "edX Pattern Library". This will also be changed throughout our repo wiki docs.
- - -
- - -
=> Simplify README & Transfer How-to Info to Wiki

CHANGELOG.md, bower.json, package.json, pattern-library/sass/global/_settings.scss, pattern-library/sass/patterns/_icons.scss
I've fixed a couple of issues that are blocking the usage of the Pattern Library in edx-platform:
1. I've introduced a new variable $edx-pattern-library-path that points to the root of the pattern library's assets. This allows a consuming library to override just this one variable and then have fonts, images etc be served from the correct location.
2. I fixed one instance where an edx-icons font was not referenced via $edx-icons-font-path.
These changes are needed to support https://github.com/edx/edx-platform/pull/11268.
=> Fix path loading issues when consuming the Pattern Library

pattern-library/html/boilerplate-blank-RTL.html, pattern-library/html/boilerplate-blank.html, pattern-library/html/boilerplate-header+footer+content+nav.html, pattern-library/html/boilerplate-header+footer.html
**This work adds in some basic example HTML boilerplates with the purpose of:**
* Communicating how to apply the HTML Styleguide (https://github.com/edx/ux-pattern-library/wiki/Styleguide:-HTML) into base cases
* Giving developers and template-creators a starting point for how to organize their DOM and what basic properties, settings, and elements to start with
* Showing different options for different configuration and base UI rendering support (e.g. favicon, touch icon, IE/older browser warning). These should be removed/used on a case-by-case basis.
**What this work does not do:**
* Create production-ready templates for apps - these still need to be adjusted to fit the flow/content/settings for each application
* Point to production ready assets (CSS, JS) - links and references need to …
=> HTML Boilerplates - For Kickstarting using the UXPL

_posts/patterns/2016-01-28-alerts.md, gulp/config.js, gulp/tasks/styles.js, pattern-library/sass/edx-pattern-library-ltr.scss, pattern-library/sass/edx-pattern-library-rtl.scss, pattern-library/sass/global/_lib.scss, pattern-library/sass/global/_ltr.scss, pattern-library/sass/global/_rtl.scss
Clean up the way that library imports are handled, to make it easier on consumers. Now the assumption is that the Pattern Library's node_modules directory will be added to the Sass load path, which means that references can be relative and can work in any client.
@AlasdairSwan @bjacobel @dan-f please review.
=> Clean up library import logic

pattern-library/js/edx-icons.js
To make the edx-icons available for use in both LMS and Studio, I needed to ensure that the file loads with or without RequireJS. This work makes that happen.
=> Ensuring icons work with or without RequireJS

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
I've created a GitHub pull request template that will be automatically added to all PRs created going forward. For the content, I merged our recommend pull request template with the new standard one that Cale merged today:
https://github.com/edx/cookiecutter-django-ida/pull/21/files
FYI, you can read more about the GitHub functionality here:
https://github.com/blog/2111-issue-and-pull-request-templates
@AlasdairSwan @dsjen @dan-f Please review.
=> Add a GitHub pull request template

gulp/tasks/pldoc.js
I fixed a bug when I tried using the new gulp task for publishing to GitHub Pages. I'd copied the task from the UI Toolkit, but the configuration is slightly different there.
I've verified the change by using the task to update [http://ux.edx.org/](http://ux.edx.org/)
=> Fix configuration typo in doc publishing

pattern-library/sass/global/_settings.scss
Update ``$baseline`` to specify that its value is in pixels, primarily for compatibility with edx-platform. It also seems to make more sense to specify the unit (the baseline is 20 what?).
I manually verified that the Jekyll documentation still generates okay.
=> Update $baseline to specify 'px'

gulp/tasks/watch.js, package.json, pattern-library/sass/_edx-pattern-library.scss, pattern-library/sass/patterns/_breadcrumbs.scss, pldoc/_components/breadcrumbs.md, pldoc/_includes/examples/breadcrumbs-js.html, pldoc/static/js/pattern-library-doc.js
Refs [TNL-4599](https://openedx.atlassian.net/browse/TNL-4599)
Adds breadcrumb styling and pattern example. Uses JS components added to the UITK in [#72](https://github.com/edx/edx-ui-toolkit/pull/72).
http://ux-test.edx.org/bjacobel/breadcrumbs/
=> Add breadcrumbs pattern

pldoc/404.html, pldoc/_components/alerts.md, pldoc/_components/buttons.md, pldoc/_components/forms.md
- Update icon class to font awesome on Alerts sample page.
- Update icon class to font awesome for the search icon on Form sample page.
[Preview](http://ux-test.edx.org/alisan/alert-icons-missing-in-pattern-library/components/alerts/)
=> Fix icon class to use font awesome on Alerts and Form sample pages

pattern-library/sass/global/_settings.scss, pattern-library/sass/patterns/_icons.scss
There is one old edx-icons font path still exist in the _icon.scss. This PR is to remove it.
[Preview](http://ux-test.edx.org/alisan/icon-font-family-fix/)
=> icon font family and path overlooked

.eslintignore, gulp/.eslintrc.json, gulp/config.js, gulp/tasks/browserSync.js, gulp/tasks/build-development.js, gulp/tasks/build-production.js, gulp/tasks/clean.js, gulp/tasks/default.js, gulp/tasks/demo_scripts.js, gulp/tasks/demo_styles.js, gulp/tasks/fonts.js, gulp/tasks/images.js, gulp/tasks/jekyll-build.js, gulp/tasks/jekyll-rebuild.js, gulp/tasks/pldoc.js, gulp/tasks/scripts-lint.js, gulp/tasks/scripts-uglify.js, gulp/tasks/scripts.js, gulp/tasks/watch.js, gulp/util/bundleLogger.js, gulp/util/gitUtils.js, gulp/util/handleErrors.js, gulp/util/webpack.js, gulpfile.js, package.json, pldoc/demo/static/js/pattern-library.js, webpack.config.js, webpack.css.config.js
Previously we were linting only a small subset of "source" files and not including some directories that contained a lot of JS code (notably `./gulp`). This lints the whole repo, and fixes all the existing lint violations. 
(I went ahead and did this because my editor has no way to turn off linting on a per-file basis, and all the red in the gulp scripts was making it hard to concentrate while debugging other issues.)
=> Make entire repo pass ESLint

gulp/util/webpack.js
Fix [FEDX-217](https://openedx.atlassian.net/browse/FEDX-217). My previous changes to the Gulp tasks that run Webpack somehow* resulted in the `gulp preview` command not sending any Javascript to preview sites
*The fact this happened is weird and strange - all I did was move two require calls to the top of the file, where they probably should be. Some kind of timing issue.
[Sandbox here.](http://ux-test.edx.org/bjacobel/fix-things/)
FYI @clrux 
=> Fix previewing issues

CHANGELOG.md, bower.json
Release branch. Working branch already had thumbs, but neglected to include the bower and CHANGELOG updates. This brings those two things in.
=> Changlog and production build

pattern-library/sass/_normalize.scss, pattern-library/sass/patterns/_forms.scss, pldoc/_components/forms.md
Updates styling of `<button>`s immediately following `<input>`s to remove spacing between them and match styling and sizing.
http://ux-test.edx.org/bjacobel/search-tweaks/components/forms/
(old: [spacing between box and button, rounded corners, mismatched sizes](https://i.bjacobel.com/20160801-zcawc.png))
Checked in FFX, Safari and Chrome and confirmed the styling is consistent.
- ~~Manually test right-to-left behavior.~~ N/A
=> Update styling for search box

pattern-library/sass/patterns/_buttons.scss, pldoc/_components/buttons.md, pldoc/static/sass/_components.scss
I've pushed up some clean ups to the button styles, based upon problems that @rlucioni saw yesterday on Programs. In particular, links styled as buttons were incorrectly showing an underline on hover, and the default button had the wrong color on hover.
I've also reorganized the documentation a little, and pushed up a preview here:
http://ux-test.edx.org/andya/quick-fixes/components/buttons/
FYI @rlucioni @AlasdairSwan @schenedx
=> Clean up button styles and documentation

package.json, pattern-library/sass/patterns/_forms.scss
[TNL-5188](https://openedx.atlassian.net/browse/TNL-5188)
These are a couple of small fixes to the Pattern Library to fix color contrast issues with form elements. Once this lands and is released, I will need to cut a PR against the edx-platform release candidate.
You can see the updated documentation here:
http://ux-test.edx.org/andya/fix-input-background-colors/components/forms/
FYI: @macdiesel @AlasdairSwan 
=> Address color contrast issues with form elements

.zappr.yml, AUTHORS
Adds config for [Zappr](https://zappr.opensource.zalan.do), a system for enforcing the pull request approval process. After this merges (and I flip the switch on their site), every PR will require at least one person from each of the following groups to give their approval.
__UX__
- @chris-mike
- @roderickmorales
- @lizc577
__FedX engineers__
- @andy-armstrong
- @AlasdairSwan
- @alisan617
- @bjacobel
- @dsjen
__a11y__
- @clrux
- @cptvitamin 
Let me know if I forgot anyone (basing this off the org charts).
Approval is given with one of the following phrases:
- :thumbsup: (`:thumbsup:`)
- :+1: (`:+1:`)
- :shipit: (`:shipit:`)
- "LGTM" or "lgtm"
Let's try it out - I'll merge this when I have one approval from each of the three groups above. (The bot won't actually work until the config is in …
=> Configure Zappr (pull request approval bot)

pattern-library/js/select-replace.js, pattern-library/sass/_normalize.scss, pattern-library/sass/patterns/_forms.scss
Bug fix only
- Fix RTL margin side of the search button
- Fix the Down Arrow in icon span in dropdown menu
- Fix the search text input box in Safari
- Remove the -webkit input[type="search" pseudo clear icon in search text input as it does not align well across all browser
[FEDX-228](https://openedx.atlassian.net/browse/FEDX-228)
[FEDX-242](https://openedx.atlassian.net/browse/FEDX-242)
[FEDX-243](https://openedx.atlassian.net/browse/FEDX-243)
[Forms](http://ux-test.edx.org/alisan/fix-searchfield-webkit-appearance/components/forms/)
=> searchfield in safari and icon in dropdown menu

package.json
Fix two minor issues:
- `webpack-dev-server` was in `dependencies`, not `devDependencies`
- `webpack-stream` was no longer used.
=> Reorganize webpack deps

pldoc/_design_elements/colors.md
Grids page on UXPL doc was trying to shove 14 columns into a 12-column row for a few of the color sets. (Screenshot below.) This somehow worked in the old grid system, but doesn't anymore.
Fixed on: 
http://ux-test.edx.org/bjacobel/colors-page-grids/design_elements/colors/
=> Fix overfull grids on colors page

pattern-library/sass/patterns/_layouts.scss, pldoc/_design_elements/grid.md
Prebuilt layouts at screen sizes < 768 px were broken after my most recent UXPL PR (new grid system).
It's pretty obvious, don't know why I didn't catch it. Live on http://ux.edx.org/design_elements/layouts/
Preview sandbox with fix: http://ux-test.edx.org/layouts-responsive-fix/design_elements/layouts/
This will need to go out as 0.17.1 and be integrated into platform before the next release as it's causing [TNL-5934](https://openedx.atlassian.net/browse/TNL-5934)
=> Fix issue with prebuilt layouts below 768px

pattern-library/sass/global/_settings.scss, pattern-library/sass/patterns/_buttons.scss, pldoc/_components/buttons.md
[FEDX-231](https://openedx.atlassian.net/browse/FEDX-231)
Accessility updates to buttons:
* Darkened hover/focus colors
* Darked link read color
* Updated disabled button styling on inverse background
Preview: http://ux-test.edx.org/dsjen/a11y-buttons/components/buttons/
* Confirm color is darker when hovering over buttons.
* Confirm color of links is darker when "read."
* Confirm under link appears when hovering over links.
* Confirm disabled button is correct in inverse background state.
I'm looking for two developer 👍  in addition to @chris-mike as product reviewer.  If you've been tagged for review, please check your corresponding box once you've given the :+1:.
@chris-mike -- Please confirm that this is what you were expecting.
=> Updated buttons to be more accessible.

package.json
Bourbon 4.3.0 adds a bunch of deprecation warnings for features that will be removed in Bourbon 5.0. These warnings cause _tons_ of unhelpful logging output - [24,000 lines of log spew](https://openedx.atlassian.net/browse/FEDX-287?focusedCommentId=246690&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-246690) for some testing runs.
I don't expect us to update to Bourbon 5.0 any time soon (it's probably more likely that we'd remove Bourbon rather than using it in the coming new iteration of the pattern library) so this just pins the version down to < 4.3.
(Note that there are still some deprecation warnings output using Bourbon 4.2.7 when running `paver compile_sass` in platform, but it's like 12 warnings vs. thousands of them. I'll follow this up in …
=> Disallow installation of bourbon >= 4.3

.github/workflows/ci.yml, package-lock.json
=> build: add package.json lock file
